name: Release

on:
  pull_request:
    branches:
      - main


permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: read

jobs:
  tag-check:
    name: Main Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.package-version.outputs.result }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Check tag
        id: check-tag
        uses: GrantFS/actions-tag-check@0.0.1

      - name: Is this tagged
        run: echo ${{ steps.check-tag.outputs.tagged }}

